# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sortedIndex <- function(x) {
    .Call(`_szKendall_sortedIndex`, x)
}

compare_self <- function(x) {
    .Call(`_szKendall_compare_self`, x)
}

tieXcount <- function(x) {
    .Call(`_szKendall_tieXcount`, x)
}

tieXYcount <- function(x, y) {
    .Call(`_szKendall_tieXYcount`, x, y)
}

kendall_discordant <- function(x, y) {
    .Call(`_szKendall_kendall_discordant`, x, y)
}

kendall_distance_cpp <- function(x, y) {
    .Call(`_szKendall_kendall_distance_cpp`, x, y)
}

weight <- function(n, diff) {
    .Call(`_szKendall_weight`, n, diff)
}

weight_sz <- function(diff) {
    .Call(`_szKendall_weight_sz`, diff)
}

cal_weight_vec <- function(n) {
    .Call(`_szKendall_cal_weight_vec`, n)
}

cal_weight_sz_vec <- function(n) {
    .Call(`_szKendall_cal_weight_sz_vec`, n)
}

countPairsWithDiffK <- function(arr, n, k) {
    .Call(`_szKendall_countPairsWithDiffK`, arr, n, k)
}

szkendall_cpp <- function(Y1, Y2, Y1_sz_idx, Y2_sz_idx, weight_vec, weight_sz_vec, type = "Nodiag") {
    .Call(`_szKendall_szkendall_cpp`, Y1, Y2, Y1_sz_idx, Y2_sz_idx, weight_vec, weight_sz_vec, type)
}

weight1_sz <- function(diff) {
    .Call(`_szKendall_weight1_sz`, diff)
}

cal_weight_sz_vec1 <- function(n) {
    .Call(`_szKendall_cal_weight_sz_vec1`, n)
}

szkendall1_cpp_Kendallpart <- function(Y1, Y2, Y1_sz_idx, Y2_sz_idx, weight_sz_vec, type = "Nodiag") {
    .Call(`_szKendall_szkendall1_cpp_Kendallpart`, Y1, Y2, Y1_sz_idx, Y2_sz_idx, weight_sz_vec, type)
}

szkendall1_cpp_SZpart <- function(Y1, Y2, Y1_sz_idx, Y2_sz_idx, weight_sz_vec, type = "Nodiag") {
    .Call(`_szKendall_szkendall1_cpp_SZpart`, Y1, Y2, Y1_sz_idx, Y2_sz_idx, weight_sz_vec, type)
}

