# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cal_weight_vec3 <- function(n) {
    .Call(`_szKendall_cal_weight_vec3`, n)
}

cal_weight_sz_vec3 <- function(n) {
    .Call(`_szKendall_cal_weight_sz_vec3`, n)
}

cal_weight_vec1 <- function(n) {
    .Call(`_szKendall_cal_weight_vec1`, n)
}

cal_weight_sz_vec1 <- function(n) {
    .Call(`_szKendall_cal_weight_sz_vec1`, n)
}

cal_weight_sz_vec2 <- function(n) {
    .Call(`_szKendall_cal_weight_sz_vec2`, n)
}

szkendall <- function(Y1, Y2, Y1_sz_idx, Y2_sz_idx, weight_vec, weight_sz_vec, type = "Nodiag") {
    .Call(`_szKendall_szkendall`, Y1, Y2, Y1_sz_idx, Y2_sz_idx, weight_vec, weight_sz_vec, type)
}

szkendall1 <- function(Y1, Y2, Y1_sz_idx, Y2_sz_idx, weight_vec, weight_sz_vec, type = "Nodiag") {
    .Call(`_szKendall_szkendall1`, Y1, Y2, Y1_sz_idx, Y2_sz_idx, weight_vec, weight_sz_vec, type)
}

szkendall2 <- function(Y1, Y2, Y1_sz_idx, Y2_sz_idx, weight_sz_vec, type = "Nodiag") {
    .Call(`_szKendall_szkendall2`, Y1, Y2, Y1_sz_idx, Y2_sz_idx, weight_sz_vec, type)
}

